spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topic1
        output:
          destination: topic2
      kafka:
        binder:
          brokers: 10.12.47.42:9092
server:
  port: 8532
